### ISSUE TITLE
Support for recurrent layers

### ISSUE THREAD

**Issue by sveinnpalsson** [pplonski/keras2cpp#1]
Great work, thanks a lot!
I have trained a recurrent net using keras and am looking for ways to make predictions in a c++ application.
Will support for recurrent layers be added?
Thanks

**Comment by pplonski** [comment]
Yes, I am planning to add them soon.

**Comment by danieleghisi** [comment]
Hi! Any news on this? LSTM layer support would really come in handy for me...
Thanks for the excellent work!

**Comment by ddovod** [comment]
+1 for recurrent (lstm/gru) layers, it would be awesome! Thank you a lot!

**Comment by pplonski** [comment]
I have this in my TODO - but it is soo long. I'll update you when I'll start to work on it.

**Comment by ales222** [comment]
Are there news on LSTM support??

**Comment by pplonski** [comment]
Sorry, no support for LSTM, you can try to learn LSTM with tensorflow backend, and use tensorflow c++ api for production deploy.

**Comment by gnosky10** [comment]
hi, thanks your work. I need convert keras layer (LSTM and TimeDistributed) in c++, can you help me?
