### ISSUE TITLE
app crash in example

### ISSUE THREAD

**Issue by gantoday** [pplonski/keras2cpp#20]
![image](https://cloud.githubusercontent.com/assets/7780154/25470211/c9aad6de-2b53-11e7-8ad7-d8ed9f2680ae.png)
![image](https://cloud.githubusercontent.com/assets/7780154/25470237/e1f88880-2b53-11e7-98c2-e8348907ca98.png)

**Comment by gantoday** [comment]
in my ubuntu
![image](https://cloud.githubusercontent.com/assets/7780154/25470848/b73bf76e-2b56-11e7-905e-4755601d19e3.png)

I'm just download and compile example.Where is wrong?Please help me.

**Comment by pplonski** [comment]
Hi! This code works with Theano as a backend, what is your backend?

**Comment by gantoday** [comment]
@pplonski My Windows use Tensorflow backend,Ubuntu no backend installed.

>This is a bunch of code to port Keras neural network model into pure C++.

This repo still need install backend?
I'm use my_nn_arch.json,my_nn_weights.h5,dumped.nnet under example directory,and did not run mnist_cnn_one_iteration.py.

**Comment by pplonski** [comment]
OK, if you run on example data, then it should work. I've reproduced this issue and I'll fix it and let you know. Thanks!

**Comment by gantoday** [comment]
Thanks! :D

**Comment by pplonski** [comment]
Hey! Sorry that it took so long, it is fixed now. Would you try it again?

**Comment by gantoday** [comment]
It works well.Thank you!

**Comment by pplonski** [comment]
You welcome!
