### ISSUE TITLE
memory error while running example

### ISSUE THREAD

**Issue by ckirksey3** [pplonski/keras2cpp#24]
I'm able to walk through the entire example until I get to running the dumped file. When I run:
```./a.out ```

I get this error:
```Reading model from ./example/dumped.nnet
Layers 12
Layer 0 Convolution2D
Layer 0 Convolution2D
Layer 0 Convolution2D
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

Any idea what's going on?

**Comment by pplonski** [comment]
Hi there! I think that might be a Keras version problem, I assume based on PR from you that you are on 2.0? Have you tried with older Keras version?

**Comment by ckirksey3** [comment]
No, I'll give that a try and let you know.
