### ISSUE TITLE
Traceback (most recent call last):   File "keras2cpp/dump_to_simple_cpp.py", line 33, in <module>     fout.write('layer ' + str(ind) + ' ' + l['class_name'] + '\n') TypeError: string indices must be integers

### ISSUE THREAD

**Issue by tonycui0401** [pplonski/keras2cpp#27]
Hi I have got another error here:

Traceback (most recent call last):
  File "keras2cpp/dump_to_simple_cpp.py", line 33, in <module>
    fout.write('layer ' + str(ind) + ' ' + l['class_name'] + '\n')
TypeError: string indices must be integers

could you please let me know why?

**Comment by virtualenv** [comment]
Dear Tony, did you find the error ?

Thanks.

**Comment by pplonski** [comment]
This might be because of version mismatch. I was testing this on Keras version 1.2 and Thenao as backend (if I remember correctly).
