### ISSUE TITLE
Network dumping error !

### ISSUE THREAD

**Issue by stardust2602** [pplonski/keras2cpp#29]
Hi, i am trying to use your keras2cpp functions to import my Keras model into my cpp project. However, when I run the python script to dump the model into text file, I realize that all Conv2D layers dont have the matrix values displayed in the text file. 
I can send you my json and h5 files if you want. Thank you !!!

**Comment by Shreyank21** [comment]
Same Issue. Anyone to help ??

**Comment by pplonski** [comment]
Hey! There is a python script that dumps json and h5 files into text files which can be used in cpp.
