### ISSUE TITLE
does it support  'Model' model ?

### ISSUE THREAD

**Issue by wu-ruijie** [pplonski/keras2cpp#31]
I see your example is ‘Sequential’ model.
but it looks like not support  'Model' model.
thanks

**Comment by Dobiasd** [comment]
Yes, keras2cpp only supports sequential Keras models.

If you want to deploy models build with the [functional API](https://keras.io/getting-started/functional-api-guide/) you need to use for example [TensorFlow serving](https://www.tensorflow.org/serving/) or [frugally-deep](https://github.com/Dobiasd/frugally-deep) (sorry for the shameless plug ;D).

**Comment by pplonski** [comment]
Thanks for info! ;)

**Comment by Dobiasd** [comment]
Hi @pplonski :-)

Are you still actively working on deploying Keras models in C++? Since keras2cpp and frugally-deep have a similar purpose, perhaps we two could collaborate and provide something even better?
