### ISSUE TITLE
how can I use colored images inputs?

### ISSUE THREAD

**Issue by olivino** [pplonski/keras2cpp#32]
how can I use your implementation with colored inputs, rgb images for example?

**Comment by pplonski** [comment]
And how have you tried to use it? Have you?

I've checked and DataChunk2D can handle images with depth > 1, so you should be able to run it on rgb images.

**Comment by olivino** [comment]
thanks for the quick reply, I made a mistake thinking that the first parameter on .dat was about the amount of images and not about the depth
