### ISSUE TITLE
issue while testing the test_run.sh file

### ISSUE THREAD

**Issue by Prajapati-IIT** [pplonski/keras2cpp#50]
Dear Expert,
I followed these steps and completed the first four steps now I want to test dumping for your network, and use test_run.sh script but i do not understand how it will run and how to get the C++ code file which is used in fluent. please describe it.

**Comment by pplonski** [comment]
This is very old code, it is working only for Keras with Theano backend.

The idea is to export neural network weights from Keras format into some custom format, which can be loaded in C++ program.
