### ISSUE TITLE
Dump model in binary file

### ISSUE THREAD

**Issue by Tauranis** [pplonski/keras2cpp#7]
Hello,
First of all I'd like to thank you for making this library.
It has been very handy for me.
However, I have a ~550MB Keras model(weigths) that turns into ~1.6GB plain text model to use with keras2cpp.
Is it too much difficult to make the library be able to read a binary file?
If I make it, I'll add a pull request.
Thanks in advance.

**Comment by pplonski** [comment]
Hi! It is not hard to be able to read binary files - I just keep text files for debug purposes. It will be nice if we can support both: text files and binary files and read base on file extension? What do you think? In this area pull request is welcome.

**Comment by Tauranis** [comment]
Yeah. Sure

Just another thing. The current code does not give support for border_mode='same' on Convolution2D layers. I got an error and all my outputs were -nan =P.
If I fix it, I'll make a pull resquest.

**Comment by pplonski** [comment]
I already fixed this, please check if it is working for you ;)
