### ISSUE TITLE
Compute_output and memory management

### ISSUE THREAD

**Issue by falvaro** [pplonski/keras2cpp#8]
When computing the output of a model with
`KerasModel::compute_output(keras::DataChunk *dc)`
the input DataChunk (dc) is deleted. Since this DataChunk is created somewhere else, I think it is better to let the code that created the object to free it. To do this, a single line should be added to the code to prevent this first input to be deleted, [here](https://github.com/pplonski/keras2cpp/blob/master/keras_model.cc#L316).

Add a condition to
`delete inp;`
like
`if( inp != dc )
      delete inp;`

**Comment by pplonski** [comment]
Thanks! I have changed this and now input DataChunk is deleted in main function. Thanks!
